logging:
  config: classpath:config/logback-config.xml

spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9092/~/test
      password: ''
      username: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: false
  batch:
    jdbc:
      initialize-schema: ALWAYS
  task:
    scheduling:
      pool:
        size: 2
  main:
    allow-bean-definition-overriding: true

server:
    port: 7072

springfox:
  documentation:
    auto-startup: false
    enabled: false

com.kabang:
  scheduling:
    cron:
      merge-popular-keyword: 0/10 * * * * ?
      remove-search-keyword: 0/20 * * * * ?
  batch:
    search-keyword-store-expire-day: 1
    merge-popular-keyword-batch-size: 500
    remove-expire-data-batch-size: 50

